### ISSUE TITLE
Recover 0Announce menu entrence

### ISSUE THREAD

**Issue by huan** [zixia/bbs.zixia.net#6]
![image](https://user-images.githubusercontent.com/1361891/105637162-00bf0480-5ea7-11eb-96e2-c5ff1ded8833.png)

the `.Names` need to be generated?

**Comment by realkcn** [comment]
After generate 0Announce/.Names and groups/.Names , it will recover.

**Comment by realkcn** [comment]
recovered .Names by scripts:
````shell
#!/bin/sh

function gen_item
{
  dir=$1
  number=$2
  title=$(head -2 $dir/.Names|tail -1|sed 's/^# Title=\(.*\)$/\1/g')

  echo "Name=$title"
  echo 'Attach=0'
  echo "Path=~/$dir"
  echo "Numb=$number"
  echo '#'
}

cd $1
numb=1
echo '#'
echo "# Title=$2"
echo '#'

for directory in `find . -mindepth 2 -maxdepth 2 -name .Names|sed 's/^\.\/\(.*\)\/.Names$/\1/g'` ;
do
  gen_item $directory $numb
  numb=$((number+1))
done
````

generate groups/.Names:
````shell
cd ~/0Announce/groups
bash ~/tmp/KCN/gen_names.sh . 讨论区精华 > .Names
````

then generate 0Announce/.Names
````shell
cd ~/0Announce
bash ~/tmp/KCN/gen_names.sh . 本站精华区 > .Names
````

**Comment by huan** [comment]
精华区目录出现了～ 虽然看起来非常奇怪，但是好像就是当年的样子吧。。。

K core 英明神武，一统江湖！

![image](https://user-images.githubusercontent.com/1361891/105671298-6f3ea980-5f1d-11eb-8e68-e3c251ac42d3.png)
