### ISSUE TITLE
版面帖子的已读/未读标记无法更新

### ISSUE THREAD

**Issue by huan** [zixia/bbs.zixia.net#7]
![image](https://user-images.githubusercontent.com/1361891/105637551-2220f000-5ea9-11eb-8e4b-8858a85c92ab.png)

阅读过帖子后，当时显示为已读。

但是如果退出版面，然后重新进入，会发现帖子还是未读状态。

**Comment by realkcn** [comment]
It's gzopen error.
````c
    if ((brcfile = gzopen(dirfile, "rb6")) == NULL)
        if ((brcfile = gzopen(dirfile, "w+b6")) == NULL)
            return 0;
````

gzopen only support "r" for opening or "w" for writing.Using "w+" for both will result an error.
Remove "+" will fix this bug.

**Comment by huan** [comment]
Thanks for the quick fix!

Link to https://github.com/zixia/bbs.zixia.net/commit/f1d0e6d36763ead65c03b106856c1dfcbebd3246

**Comment by huan** [comment]
Updated online server and I can confirm that this issue has been resolved.
